[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# pre_splash context
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "G.GAME.hands[text].visible = true"
position = 'after'
match_indent = true
payload = '''
SMODS.calculate_context({pre_splash = true, full_hand = G.play.cards, scoring_hand = scoring_hand, in_scoring = true, ignore_other_debuff = true}, effects)
'''